version: "3.2"

services:
  postgres:
    image: postgres:10.0
    hostname: postgres
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bard
      POSTGRES_PASSWORD: bard
      POSTGRES_DATABASE: bard

  app:
    build:
      context: .
    #image: barddata/bard:${BARD_TAG:-latest}
    hostname: bard
    command: /bin/bash
    depends_on:
      - postgres
    tmpfs: /tmp
    environment:
      DAKOBED_DEBUG: "true"
      DAKOBED_SECRET_KEY: "development"
    volumes:
      - archive-data:/data
      - "./bard:/bard/bard"
      - "~:/host"
    cap_add:
      - SYS_PTRACE

  api:
    build:
      context: .
    #image: barddata/bard:${BARD_TAG:-latest}
#    command: bard run -h 0.0.0.0 -p 5000 --with-threads --reload --debugger
    ports:
      - "127.0.0.1:5000:5000"
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - "./api:/usr/src/app/api"


  ui:
    build:
      context: ui
#    image: dakobedio/dakobed-ui:${DAKOBED_TAG:-latest}
#    depends_on:
#      - api
    command: npm run start
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./ui/src:/dakobedui/src"
      - "./ui/package.json:/dakobedui/package.json"
    environment:
      PORT: "8080"
      CI: "true"

volumes:
  archive-data: {}
  postgres-data: {}
  redis-data: {}
  elasticsearch-data: {}

